version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
